# Generated by Django 5.1.4 on 2024-12-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(blank=True, max_length=60, unique=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
