# Generated by Django 5.1.4 on 2024-12-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_product_active_product_created_at_product_likes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
