# Generated by Django 5.1.4 on 2024-12-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', 'name']},
        ),
    ]
