# Generated by Django 5.1.4 on 2024-12-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False, null=True)),
                ('products', models.ManyToManyField(related_name='orders', to='back.product')),
            ],
            options={
                'ordering': ['-created_at', 'reference'],
            },
        ),
    ]
