# Generated by Django 5.1.4 on 2024-12-20 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
