# Generated by Django 5.1.4 on 2024-12-20 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_orderdetails_order_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(auto_now=True)),
                ('is_closed', models.BooleanField(default=False, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name': 'Order details', 'verbose_name_plural': 'Orders details'},
        ),
        migrations.CreateModel(
            name='ArrivalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=1)),
                ('arrival', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.arrival')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.product')),
            ],
            options={
                'verbose_name': 'Arrival details',
                'verbose_name_plural': 'Arrivals details',
            },
        ),
        migrations.AddField(
            model_name='arrival',
            name='products',
            field=models.ManyToManyField(related_name='arrivals', through='back.ArrivalDetails', to='back.product'),
        ),
    ]
