# Generated by Django 5.1.4 on 2024-12-20 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_arrival_alter_orderdetails_options_arrivaldetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('payed_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(default='Cash', max_length=30)),
                ('details', models.TextField(blank=True, max_length=255, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='back.order')),
            ],
            options={
                'ordering': ['-payed_at', 'reference'],
            },
        ),
    ]
